name: Python Automation

on:
  workflow_dispatch: # Allows manual triggering of the workflow
  schedule:
    - cron: "30 4 * * *" # Runs every day at 10:00 AM IST

jobs:
  automate-naukri-task:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        python -m venv naukri_env
        source naukri_env/bin/activate
        pip install selenium

    - name: Install Chrome and ChromeDriver
      run: |
        sudo apt-get install -y software-properties-common
        wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        wget "https://storage.googleapis.com/chrome-for-testing-public/135.0.7049.42/linux64/chromedriver-linux64.zip"
        unzip chromedriver-linux64.zip
        sudo mv chromedriver-linux64/chromedriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver

    - name: Run Python Script
      env:
        NAUKRI_USERNAME: ${{ secrets.NAUKRI_USERNAME }}
        NAUKRI_PASSWORD: ${{ secrets.NAUKRI_PASSWORD }}
      run: |
        xvfb-run --auto-servernum --server-args="-screen 0 1920x1080x24" bash -c "
        source naukri_env/bin/activate &&
        python naukri_automation.py
        "